# Generated by Django 4.1.4 on 2023-01-02 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_on']},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='creaed_on',
            new_name='created_on',
        ),
    ]
